name: Code Quality Check

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: xdebug, mysqli
          coverage: xdebug

      - name: Install dependencies
        run: |
          npm install
          composer install --no-interaction --prefer-dist

      - name: Run Node tests
        run: npm run test

      - name: Run Node coverage
        run: npm run coverage

      - name: Run PHPUnit coverage
        run: |
          php -d xdebug.mode=coverage ./vendor/bin/phpunit \
            --coverage-text \
            --coverage-filter php/renderers \
            --coverage-filter php/queries \
            tests/php
